#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

main_script_path=${BASH_SOURCE[0]}
base_dir="$(dirname "${main_script_path}")"

source_files () {
  for src in "${base_dir}/"*.sh; do
    if [ "${src}" = "${main_script_path}" ]; then
      continue
    fi

    [ -f "${src}" ] && . "${src}"
  done
}

get_output_path () {
  echo "$(pwd)/$(yq read "${config_name}" --tojson | jq ".output" | tr -d \" | tr -d '\n')"
}

create_output_directory () {
  mkdir -p "$(get_output_path)"
}

get_page_names () {
  yq read "${config_name}" --tojson | jq ".pages | keys[]" | tr -d \" | tr '\n' ','
}

main () {
  config_name="${1:-"yacht.yaml"}"
  source_files
  create_output_directory
  pages="$(get_page_names)"
  for_each compile "$pages"
}

main "$@"
